### ISSUE TITLE
Ignore duplicate declarations if one of the expression's terms are prefixed

### ISSUE THREAD

**Issue by mattbasta** [mattbasta/crass#12]
I.e.:

``` css
foo {
    background: #fff;
    background: -moz-gradient(foo, bar);
}
```

should not be optimized into

``` css
foo {
    background: -moz-gradient(foo, bar);
}
```
