### ISSUE TITLE
When combining rulesets, consider `!important`

### ISSUE THREAD

**Issue by mattbasta** [mattbasta/crass#16]
https://github.com/mattbasta/crass/blob/master/test/optimizations.js#L270

Consider:

``` css
.foo {
    color: red !important;
}
p {
    color: blue !important;
}
.foo {
    font-weight: bold;
}
```

In this case, the first and third rulesets should NOT be combined into the second as usual:

``` css
p {
    color: blue !important;
}
.foo {
    color: red !important;
    font-weight: bold;
}
```

``` html
<p class="foo">What color is this text?</p>
```

In the example above, the text would be blue with the original code and red with the changed code.
