### ISSUE TITLE
Duplicate declarations are not removed after transformation

### ISSUE THREAD

**Issue by mattbasta** [mattbasta/crass#20]
``` css
#my-id .class [attribute] {
  color: #ffffff;
  border-radius: 5px;
  color: #fff;
}
```

results in

``` css
#my-id .class [attribute]{border-radius:5px;color:#fff;color:#fff}
```

with O1 on.
