### ISSUE TITLE
Identical keyframes are not combined

### ISSUE THREAD

**Issue by mattbasta** [mattbasta/crass#21]
``` css
@-webkit-keyframes spin {
  0% {
    -webkit-transform: scale(1);
    left: -10px;
    top: 0;
  }

  100% {
    -webkit-transform: scale(1);
    left: -10px;
    top: 0;
  }

  12.5% {
    -webkit-transform: scale(0.5);
  }

  25% {
    -webkit-transform: scale(1);
    left: 10px;
    top: 0;
  }

  37.5% {
    -webkit-transform: scale(0.5);
  }

  50% {
    -webkit-transform: scale(1);
    left: 10px;
    top: 20px;
  }

  62.5% {
    -webkit-transform: scale(0.5);
  }

  75% {
    -webkit-transform: scale(1);
    left: -10px;
    top: 20px;
  }

  87.5% {
    -webkit-transform: scale(0.5);
  }

}
```
