### ISSUE TITLE
CSS with null strings in identifiers are not parsed properly

### ISSUE THREAD

**Issue by mattbasta** [mattbasta/crass#32]
```css
#banner .main-banner-content .banner-des p {
  margin-bottom: 20px !important;
  margin-bottom: 19px\0 !important;
}
```
