### ISSUE TITLE
Improper transformation

### ISSUE THREAD

**Issue by mattbasta** [mattbasta/crass#59]
```css
x{a:b;c:d long}y{c:d long}
```

With O1 on, this produces:

```css
x, y {
  a: b;
  c: d long;
}
```

It should produce

```css
x {
  a: b;
}
x, y {
  c: d long;
}
```
