### ISSUE TITLE
Convert angular units to their smallest possible value

### ISSUE THREAD

**Issue by mattbasta** [mattbasta/crass#6]
Similar to how colors are processed, angular units should be processed such that the smallest representation is generated during optimization.

E.g.:

``` css
foo {
    transform: rotateX(360deg) rotateY(.25turn) rotateZ(200grad);
}
/* becomes */
foo {
    transform: rotateX(1turn) rotateY(90deg) rotateZ(.5turn);
}
```
