### ISSUE TITLE
Bad selector produced

### ISSUE THREAD

**Issue by sanmai-NL** [mattbasta/crass#67]
```sh
crass in.css --optimize --O1 --min ie10 > out.css
```

```css
a[href^="tel:"]::before {
    content: "📞 ";
}
```

```css
a[href^=tel:]:before {
 content:"📞 "
}
```

**Comment by sanmai-NL** [comment]
Same without --01.

**Comment by mattbasta** [comment]
This is fixed in 0.12.1.

**Comment by sanmai-NL** [comment]
@mattbasta:

Quotes are stripped from this:

```css
div.status[data-valid="0"] {
    background-color: #e9bdb2;
}
```
And I verified the style isn’t applied because of that, at least in Firefox Developer Edition 59.0b7 (64-bit). Attribute selectors [don’t always require quotes](https://drafts.csswg.org/selectors-3/#attribute-selectors), so this seems to be a Firefox bug then. Is there a way to prevent `crass` from making this optimization?
